### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PierreCrb**
Fix error in import

### CODE REVIEW

**Comment by iquirino** [comment]
Thank you for your help.

**Comment by iquirino** [comment]
How was your usage experience?

**Comment by PierreCrb** [comment]
> How was your usage experience?

I'm working on it, finishing my implementation and I'll share with you what I've done :)

**Comment by iquirino** [comment]
> > How was your usage experience?
> 
> I'm working on it, finishing my implementation and I'll share with you what I've done :)


Hey @PierreCrb, How is it going? Did you have a good experience?

**Pull request merged**
